import type { OverallScore, CategoryScore } from "../scoring/index.js";
import type { DiscoveredAgent } from "../checks/types.js";
import type { TrendAnalysis } from "../tracking/trends.js";

/**
 * Render the scan results as a shareable Markdown report.
 */
export function renderMarkdown(
  score: OverallScore,
  agents: Map<string, DiscoveredAgent>,
  opts?: {
    trends?: TrendAnalysis | null;
    agentsViewAvailable?: boolean;
  },
): string {
  const lines: string[] = [];

  lines.push("# Agent Hygiene Report");
  lines.push("");
  lines.push(
    `**Score: ${score.score}/100** (${score.grade})`,
  );
  lines.push("");

  // Agents
  lines.push("## Detected Agents");
  lines.push("");
  const foundAgents = [...agents.values()].filter(
    (a) => a.status !== "not-found",
  );
  if (foundAgents.length === 0) {
    lines.push("No AI coding agents detected.");
  } else {
    for (const agent of foundAgents) {
      const icon = agent.status === "configured" ? "🟢" : "🟡";
      lines.push(`- ${icon} **${agent.name}** — ${agent.status}`);
    }
  }
  lines.push("");

  // Categories
  for (const cat of score.categories) {
    if (cat.total === 0) continue;
    lines.push(renderCategoryMarkdown(cat));
  }

  // Insights (cost/usage narratives from AgentsView)
  lines.push(
    renderInsightsMarkdown(
      opts?.trends ?? null,
      opts?.agentsViewAvailable ?? false,
    ),
  );

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Category | Score | Grade | Passed |");
  lines.push("|----------|-------|-------|--------|");
  for (const cat of score.categories) {
    if (cat.total === 0) continue;
    lines.push(
      `| ${cat.category.name} | ${cat.score}/100 | ${cat.grade} | ${cat.passed}/${cat.total} |`,
    );
  }
  lines.push("");

  lines.push(
    `---\n*Generated by [agent-hygiene](https://github.com/pi0neerpat/agent-hygiene) on ${new Date().toISOString().split("T")[0]}*`,
  );

  return lines.join("\n");
}

function renderCategoryMarkdown(cat: CategoryScore): string {
  const lines: string[] = [];
  const bar = renderTextBar(cat.score);

  lines.push(
    `### ${cat.category.name} — ${cat.grade} (${cat.score}/100)`,
  );
  lines.push("");
  lines.push(`\`${bar}\``);
  lines.push("");

  for (const { check, result } of cat.checks) {
    let icon: string;
    if (result.passed) {
      icon = "✅";
    } else if (check.tier === "advisory") {
      icon = "💡";
    } else if (check.tier === "session" || check.tier === "semi-auto") {
      icon = "⚠️";
    } else {
      icon = "❌";
    }

    lines.push(`- ${icon} ${result.message}`);

    if (!result.passed && result.details) {
      lines.push(`  - _${result.details}_`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

function renderTextBar(score: number): string {
  const width = 20;
  const filled = Math.round((score / 100) * width);
  const empty = width - filled;
  return "█".repeat(filled) + "░".repeat(empty) + ` ${score}%`;
}

/**
 * Render the Insights section for the Markdown report. Always emits a
 * heading with either recommendations or an empty-state note so the
 * report's structure stays stable across runs with and without data.
 */
function renderInsightsMarkdown(
  trends: TrendAnalysis | null,
  agentsViewAvailable: boolean,
): string {
  const lines: string[] = [];
  lines.push("## Insights");
  lines.push("");

  if (!agentsViewAvailable) {
    lines.push(
      "_Install AgentsView to see cost insights from real usage data._",
    );
    lines.push("");
    return lines.join("\n");
  }

  if (!trends) {
    lines.push(
      "_AgentsView connected, but no usage recorded in the scan window._",
    );
    lines.push("");
    return lines.join("\n");
  }

  if (trends.recommendations.length === 0) {
    const d = trends.period.days;
    lines.push(
      `_No cost anomalies detected over the last ${d} day${d === 1 ? "" : "s"}._`,
    );
    lines.push("");
    return lines.join("\n");
  }

  for (const rec of trends.recommendations) {
    const marker =
      rec.priority === "high"
        ? "🔴"
        : rec.priority === "medium"
          ? "🟡"
          : "⚪";
    lines.push(`- ${marker} ${rec.message}`);
  }
  lines.push("");
  return lines.join("\n");
}
