import type { OverallScore, CategoryScore } from "../scoring/index.js";
import type { DiscoveredAgent } from "../checks/types.js";

/**
 * Render the scan results as a shareable Markdown report.
 */
export function renderMarkdown(
  score: OverallScore,
  agents: Map<string, DiscoveredAgent>,
): string {
  const lines: string[] = [];

  lines.push("# Agent Hygiene Report");
  lines.push("");
  lines.push(
    `**Score: ${score.score}/100** (${score.grade})`,
  );
  lines.push("");

  // Agents
  lines.push("## Detected Agents");
  lines.push("");
  const foundAgents = [...agents.values()].filter(
    (a) => a.status !== "not-found",
  );
  if (foundAgents.length === 0) {
    lines.push("No AI coding agents detected.");
  } else {
    for (const agent of foundAgents) {
      const icon = agent.status === "configured" ? "🟢" : "🟡";
      lines.push(`- ${icon} **${agent.name}** — ${agent.status}`);
    }
  }
  lines.push("");

  // Categories
  for (const cat of score.categories) {
    if (cat.total === 0) continue;
    lines.push(renderCategoryMarkdown(cat));
  }

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Category | Score | Grade | Passed |");
  lines.push("|----------|-------|-------|--------|");
  for (const cat of score.categories) {
    if (cat.total === 0) continue;
    lines.push(
      `| ${cat.category.name} | ${cat.score}/100 | ${cat.grade} | ${cat.passed}/${cat.total} |`,
    );
  }
  lines.push("");

  lines.push(
    `---\n*Generated by [agent-hygiene](https://github.com/pi0neerpat/agent-hygiene) on ${new Date().toISOString().split("T")[0]}*`,
  );

  return lines.join("\n");
}

function renderCategoryMarkdown(cat: CategoryScore): string {
  const lines: string[] = [];
  const bar = renderTextBar(cat.score);

  lines.push(
    `### ${cat.category.name} — ${cat.grade} (${cat.score}/100)`,
  );
  lines.push("");
  lines.push(`\`${bar}\``);
  lines.push("");

  for (const { check, result } of cat.checks) {
    let icon: string;
    if (result.passed) {
      icon = "✅";
    } else if (check.tier === "advisory") {
      icon = "💡";
    } else if (check.tier === "session" || check.tier === "semi-auto") {
      icon = "⚠️";
    } else {
      icon = "❌";
    }

    lines.push(`- ${icon} ${result.message}`);

    if (!result.passed && result.details) {
      lines.push(`  - _${result.details}_`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

function renderTextBar(score: number): string {
  const width = 20;
  const filled = Math.round((score / 100) * width);
  const empty = width - filled;
  return "█".repeat(filled) + "░".repeat(empty) + ` ${score}%`;
}
